### ISSUE TITLE
Not applying correctly on Windows 10

### ISSUE THREAD

**Issue by psydex** [riverar/uxstyle#25] opened 2016-05-25 20:47 UTC
I just installed UxStyle, placed theme in Resources/Themes, applied but nothing changed beside few minor colors changes. Service is running - I checked. What am I doing wrong?

Demonstration: https://gfycat.com/PleasedImmaterialFulmar

**Comment by CHEF-KOCH** [comment] 2016-06-02 13:27
You need to write down which version you exactly use (cmd -> winver) because in newer previews it may not work anymore and needs to be fixed.

**Comment by psydex** [comment] 2016-06-02 14:35
`Version 1511 (OS Build 10586.318)`

**Comment by CHEF-KOCH** [comment] 2016-06-02 14:39
Then this ticket is a duplicate of #21. Try this [workaround](https://github.com/riverar/uxstyle/issues/21#issuecomment-218798946).

**Comment by riverar** [comment] 2016-08-19 16:11
Is this a fresh Windows install?

**Comment by riverar** [comment] 2017-01-14 11:45
Closing due to age, file a new issue if needed.

**Closed as completed by riverar** 2017-01-14 11:45 UTC
