### ISSUE TITLE
No longer working on Windows 10 (November Update / Build 10586 / v1511)

### ISSUE THREAD

**Issue by blackwind** [riverar/uxstyle#21] opened 2015-11-22 00:52 UTC
UxStyle is currently broken on Windows 10 systems with the November Update. Can we expect a fix any time soon?

**Comment by riverar** [comment] 2015-11-23 02:36
This is a new development in Windows. Investigating fix to uxinit.

**Comment by blackwind** [comment] 2015-12-06 20:58
If it helps, [these files] are working with the latest update.

_Removed link - Rafael_

**Comment by riverar** [comment] 2015-12-06 21:05
Yeah these work because it's replacing system files with older copies that omit the change from Microsoft. (I removed the link as I don't condone the use of old binaries.)

**Comment by WindowsX** [comment] 2015-12-07 10:34
Glad to hear you're working on this. :)

**Comment by Upgrad3** [comment] 2015-12-11 19:32
Any news ? i have a test machine setup if you need anything testing ?

**Comment by MrGRiM01** [comment] 2015-12-15 11:37
Very eager for this update, I hate using these old patched files, been using Uxstyle for years now, I also donated for the development on Windows 8, if you need more donations for development I am more then happy to help.

**Comment by riverar** [comment] 2015-12-17 18:59
Thanks for the offers, I'll definitely get a test build up soon. I'm a few days away from finishing some side schooling, then I'll have a bit more time to wrap this up.

Short term hacks:
1. Rename your msstyle to aero.msstyles and shove it into a sub-directory named "aero".
2. Create \aero\aero.msstyles\ folder structure and drop your theme inside. So, for example, install your custom theme to \Windows\Resources\Themes\aero\aero.msstyles\My Theme\mytheme.msstyle

**Comment by illusion1k** [comment] 2015-12-17 20:31
Hm maybe I'm doing something wrong, but windows won't let me make a folder called "aero.msstyles", It tells me that there is a file with the same name in the "aero" folder already so I can't do that.

**Comment by riverar** [comment] 2015-12-17 20:35
Create a folder called \Hack\ then do all your work inside that then. e.g. Windows\Resources\Themes\Hack\aero\aero.msstyles\My Theme\mytheme.msstyle

**Comment by eversins** [comment] 2015-12-18 15:16
Caution with the hack, even though it worked while using the system, after a reboot windows would not start. I had to load the recovery shell before boot and manually delete the created files.

Thanks riverar for your work, can't wait for the update!

**Comment by MrGRiM01** [comment] 2015-12-18 18:43
Uxstyle is working fine again on the latest Rs1 release preview, themes can be selected from the personalization menu as normal, note that older themes will not work, only new themes made on Rs1

**Comment by MrGRiM01** [comment] 2015-12-23 19:55
1. Rename the default C:\Windows\Resources\Themes\aero\aerolite.msstyles to aerolite.msstyles.bak
2. Make a new folder in C:\Windows\Resources\Themes\aero\ called aerolite.msstyles
3. Put your theme in the aerolite.msstyles folder C:\Windows\Resources\Themes\aero\aerolite.msstyles\My Theme\My Theme.msstyles
4. Make sure your .theme file uses this new directory.
5. Select your theme from the personalization menu.

**Comment by eversins** [comment] 2015-12-24 13:43
Thanks again for the suggestion, I followed your steps exactly, but the same error happend again, after windows boot the screen flickers in white/black.
Until I reboot it works perfectly. To rename the aerolite.msstyles I had to take ownership, maybe that is the problem? I use Gray10 by gsw953 btw.

**Comment by MagicAndre1981** [comment] 2015-12-28 20:23
@MrGRiM01 

thanks, now I got the 3rd party Win7 theme working in Win10 Th2. Thanks :+1:

**Comment by Gevil** [comment] 2016-01-01 15:03
I can confirm @evetek 's issue.
I have followed your steps @MrGRiM01 and applying the theme works.
However the problem is when rebooting with the applied theme the screen will keep flickering and you can not start windows again, not even safe mode. I could only start up a command prompt from troubleshooting and manually delete the applied theme and revert the changes from @MrGRiM01 's comments. And then it would boot up again.

**Comment by MrGRiM01** [comment] 2016-01-01 15:35
Not sure why you guys are having that problem, I have been using this method and myself and others are having no problems with it, I have more detailed information on my site if your interested http://virtualcustoms.net/showthread.php/70555-Uxstyle-and-Theme-Signature-Bypass-for-Windows-10-TH2-AKA-1511-AKA-10586

**Comment by riverar** [comment] 2016-01-01 18:49
The flickering issue occurs whenthe theme you're using is missing resources for that version of Windows. I've said time and time again that msstyles are NOT forward or backward compatible. Contact the theme author for an updated msstyle.

**Comment by illusion1k** [comment] 2016-01-01 19:03
@riverar, when uxstyle gets updated, will it allow us to use any win10 theme or just the ones compatible with the most recent win10 version? If MS keeps doing this it will really hurt theme creators if they have to update all their work everytime microsoft does this.

**Comment by riverar** [comment] 2016-01-01 19:54
msstyles are just fancy dictionaries of resources for Windows. The authors must stay on top of updates and provide msstyles that match the OS build they're customizing.

I'll take an action to investigate maybe hooking the theme application workflow and ABORT when an invalid msstyle is detected, assuming an invalid msstyle can even be detected. Aside from the recent "aero.msstyles" checks added to TH2 (but removed in RS1), this isn't really a UxStyle concern.

**Comment by eversins** [comment] 2016-01-02 03:42
I am using the updated theme TH2 1511 theme (Gray10-v2 by gsw953) but I get the flickering.
@Gevil have you found the cause of you problem or were you using an old theme?

**Comment by riverar** [comment] 2016-01-02 03:47
Was that theme updated for the BUILD of windows you're using? Or are you on vanilla TH2?

**Comment by MrGRiM01** [comment] 2016-01-02 04:00
I have not tested Gray10 so have no idea what he did to get it working on TH2, try one of mine though, they were made from the TH2 msstyles http://virtualcustoms.net/showthread.php/70419-Windows-10-Black-Edition-TH2

I am also currently working on some import scripts and I can now import Windows 7  8 and 10RTM themes to Th2 and I can import 8 and 10TH2 themes to RS1, imports can take as little as 20 seconds depending on the OS your importing from.

**Comment by eversins** [comment] 2016-01-02 13:44
I am sorry guys, I was on the wrong build. I feel stupid, must be the stress in the last two month..
Thanks for your help!

So just tried, same problem.. the build version now match. Maybe my theme folder is just messed up and does not get fixed by sfc /scannow. Oh well, guess I will have to continue to use my High Contrast theme.
I don't get how MS can not release a proper a Dark Theme or theming engine, wich I see as a medical necessity.

**Comment by illusion1k** [comment] 2016-01-02 20:45
@evetek Yep. Specially if you have a decent bright ips monitor, win10 default theme is so bright that it burns my eyes. Using dark wallpapers doesn't help much either. I'm thinking about rolling back to win 8.1 until this gets sorted.

**Comment by eversins** [comment] 2016-01-03 03:10
@illusion1k I made a High Contrast theme for the mean time, its not perfect, but good enough for me.
http://eversins.deviantart.com/art/Grey-Windows-10-theme-High-Contrast-582035597

@riverar feel free to delete this post if you don't want it in your tracker, just trying to help. Keep up the good work.

**Comment by riverar** [comment] 2016-01-03 03:24
@evetek These posts don't bother me. Did the workaround work w/ a build-matching msstyle now? Or are you still having problems?

**Comment by eversins** [comment] 2016-01-03 03:41
@riverar Great. Unfortunately the workaround did not work with matching build numbers, I got the same flickering as before, maybe my default MS themes are somehow messed up. As mentioned I did do an integrity check of system files (sfc /scannow), but I don't know if that checks theme files though.

**Comment by Gevil** [comment] 2016-01-04 15:41
@riverar Yeah i realize that is the issue, but the problem is the this occurs with themes that were created for TH2 Windows 10 versions and they are not outdated themes.
I have tried with multiple themes of course so I'm not pulling this out of my butt :\

@evetek I believe i have the same issue that you have, but i can't identify what is it exactly.

The flickering still occurs, would love to test new builds/workarounds, but nothing worked so far, including a complete reinstallation of Win10 TH2.

I am currently using a custom High Contrast theme aswell that I made.

**Comment by riverar** [comment] 2016-01-04 17:46
@Gevil A theme that says it was created for "TH2" is too vague. These msstyles need to match down to the build #. Also, the author could be wrong. The flickering is absolutely related to an msstyle that doesn't match. Try other themes.

**Comment by blackwind** [comment] 2016-01-05 02:09
So, does the existence of this workaround mean we won't be getting a UxStyle update for TH2? Or is that still in the works?

**Comment by riverar** [comment] 2016-01-05 02:10
@blackwind Still in the works!

**Comment by Gevil** [comment] 2016-01-05 14:09
@riverar Thanks for the info, I didn't realize that MS would change msstyles so drastically between these larger updates like TH2. It's really weird though because my build number is still reported as 10586 from windows.

**Comment by illusion1k** [comment] 2016-01-05 14:47
@Gevil TH2 version is 10586. Win10 RTM is 10240. There were some updates after TH2, but I don't know if it affected the msstyles files. The latest win10 version is 10586.36.

If microsoft really wants to keep this model of constantly updating windows with newer versions every few months, they really gotta think about a way to change how themes work.

**Comment by Revan114** [comment] 2016-01-12 07:04
Hey, so how's the build coming? I upgraded to Windows 10 today and this fucking white shit is really pissing me off. It's so BRIGHT.

**Comment by Dr-Xperience** [comment] 2016-01-16 10:52
@MrGRiM01 Umm your website doesn't seem to render well at 1366*768. I tried it with edge/firefox I am getting the attached preview.
![screenshot 8](https://cloud.githubusercontent.com/assets/6042296/12371961/11d2f016-bc6c-11e5-9aa4-fc68a8c0bd8d.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/6042296/12371963/2caf5262-bc6c-11e5-9244-fc69974265df.png)

@riverar Sorry for putting above mention here (Deep Apologies, currently in hurry). And I can confirm that msstyles gets messed up in minor updates as well. The theme I was using was working perfectly fine in build 10586.36( Then after one or two months of no internet (Work trip) ). Windows updated with cumulative update and current version is 10586.63. Reboot and bam flicker screen. I had to carry out System image recovery to fix my system.

**Comment by riverar** [comment] 2016-01-16 10:54
Thanks for the confirmation that msstyles are not compatible across builds, something I've trumpeted for years ;) This isn't a UxStyle issue, sadly. The theming community needs to band together and fix this issue, with maybe a theme manager.

**Comment by illusion1k** [comment] 2016-01-16 12:33
The only thing that could fix this for good would be a tool that can allow us to easily change the build version of a msstyles. Microsoft is pumping new versions faster and faster, so we either fix this with a tool or theme creators will be forced to update their themes everytime a new version shows up.

**Comment by fooger** [comment] 2016-01-16 14:57
Hello. There are some news about program update for TH2?)
Thank`s!

**Comment by Dr-Xperience** [comment] 2016-01-17 03:30
@illusion1k How can we edit msstyles. I mean how to change build version of msstyles. If there is a manual method of changing version number then I suppose I can make a tool to automate that. You know something like import msstyles and bam it will be exported to the mentioned msstyles.

**Comment by illusion1k** [comment] 2016-01-17 04:01
@Dr-Xperience Resource Hacker can do it.

**Comment by riverar** [comment] 2016-01-17 04:17
This is not just a version change. msstyles change from build to build, so you'd have to make your customizations again to the newer msstyle.

**Comment by Dr-Xperience** [comment] 2016-01-17 04:30
@riverar This means just changing the version will not be enough.

**Comment by riverar** [comment] 2016-01-17 04:31
Yes. This has been the case for at least 10 years.

**Comment by Dr-Xperience** [comment] 2016-01-17 04:36
@riverar Thanks I didn't know about it. Ten years ago I was 13 lol :laughing: . Thanks again, so we do need some sort of script like the one @MrGRiM01 mentioned before.

**Comment by WindowsX** [comment] 2016-02-01 07:12
After testing aerolite hack for a while, I have to warn you guys to use this carefully. If you switch back to aero.theme without reverting this hack, you may get black screen with white flicker on startup because of missing aerolite.msstyles material.

Remember, always revert the hack before applying default aero.theme or you might get black screen flicker bug.

Regards,
Windows X

**Comment by lenny93** [comment] 2016-02-06 08:16
Not sure if this is the right place to ask this... But does anyone know if the black/blue screen bug is caused by missing or added properties on the msstyles?

**Comment by lenny93** [comment] 2016-02-06 08:44
Also, if Windows 10 gets updated, and you're using a custom msstyles, would that be a problem?

**Comment by ghost** [comment] 2016-03-03 11:39
@Dr-Xperience The reason that website shows up like that is because you're not signed into it in those screenshots. You need to make an account and sign in for the website to show up properly. Virtual Customs requires you to be signed into it in order to view links and that causes it to look kinda wonky like that if you're not signed in on there.

**Comment by dominichayesferen** [comment] 2016-05-12 15:46
For now you can always use UxStyle, then do this:
https://skinpacks.com/uxthemepatcher-for-windows-10-november-update-10586/

**Comment by dominichayesferen** [comment] 2016-05-12 15:48
BTW, the best creators for 1511 themes are sagorpirbd.deviantart.com/ & cu88.deviantart.com/

MAKE SURE THEY SAY THEY ARE FOR 1511 OR NOVEMBER UPDATE, CONSEQUENCES OF NOT DOING SO INCLUDE BLACK SCREENS, NO DWM BEFORE A BLACK SCREEN, ETC.

**Closed as completed** 2017-06-27 02:37 UTC
Labels: external, enhancement

**Comment by blackcrack** [comment] 2017-06-27 02:42
help on Reactos and you want have a pretty well support also in Themes !
(winxp 100% compatibility is first the start..)
best regards
Blacky
